---

iserver_hostname: deb10-kvm
iserver_sshkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClHs7Rk29cYGqh8jS1tkq42h1bWJfMKLvWQ5pgnxIWar4Z+ehNJyefRSL4zuYj+SZVnd2sTycSHlcFBfLEwnZNbkJ1szY6+qMXExYZBDbeZElMZZWkjTDX4tDgVAOgIGUkIkWHbwZrpbqKEzAQYuqv7vU0bRW2EXKsBX+oYYTD0w6MMA9hLih4DlSEg9ZH0W3UIyzV1+tWGWD1cWhPtPO9JSAk3IOnX9Y5FXuqgECKkiNZRM7j3AarI/AKSpqnr5x/ArrlUube67VTBCa9i/jcglMcuCvRooX1IyMEwAeXINfCwzl+yQOefvoWM6/KPfMwx9jBaxAn86ecQfO0oo9nYLBMZ7H5HvKvcyTUice8e+LXdjeGicBwRpTHarIEh9WSKL383LIk3rHWaqpMO3WTd5AZy/OV1q/Yj7IoqLoGM7mzbgEqbMe9nmxnCujERjBYrYhixHQ++GBo6XLTHGEuVhykugKalnlHuzJkmWyibssVR2zXIz3vS4plMVYBN0k= sgarland@Stephan’s-MacBook-Pro"

iserver_repos:
  - deb http://repo.myloc.de/debian buster main non-free contrib
  - deb-src http://repo.myloc.de/debian buster main non-free contrib
  - deb http://security.debian.org/debian-security buster/updates main contrib non-free
  - deb-src http://security.debian.org/debian-security buster/updates main contrib non-free
  - deb http://deb.debian.org/debian buster-updates main contrib non-free
  - deb-src http://deb.debian.org/debian buster-updates main contrib non-free
